#![allow(unused_imports, unused_attributes, clippy::all, rustdoc::all)]
//! This module contains the sol! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod hopr_announcements;
pub mod hopr_announcements_events;
pub mod hopr_announcements_proxy;
pub mod hopr_capability_permissions;
pub mod hopr_channels;
pub mod hopr_channels_events;
pub mod hopr_crypto;
pub mod hopr_boost;
pub mod hopr_token;
pub mod hopr_ledger;
pub mod hopr_ledger_events;
pub mod hopr_node_management_module;
pub mod hopr_node_safe_migration;
pub mod hopr_node_safe_migration_events;
pub mod hopr_node_safe_registry;
pub mod hopr_node_safe_registry_events;
pub mod hopr_node_stake_factory;
pub mod hopr_node_stake_factory_events;
pub mod hopr_ticket_price_oracle;
pub mod hopr_ticket_price_oracle_events;
pub mod hopr_winning_probability_oracle;
pub mod hopr_winning_probability_oracle_events;
