#################################################################################
##                      Pipeline to build on pull requests                     ##
#################################################################################
name: Build
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
permissions:
  contents: write
  actions: write
  security-events: write
concurrency:
  group: ${{ github.event.pull_request.head.ref || github.ref_name }}-build
  cancel-in-progress: true
jobs:
  build-library:
    name: Library ${{ matrix.architecture }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: x86_64-linux
            runner: self-hosted-hoprnet-bigger
            build_command: nix build -L .#lib-bindings-x86_64-linux
    uses: hoprnet/hopr-workflows/.github/workflows/build-binaries.yaml@build-binaries-v2
    permissions:
      contents: read
    with:
      source_branch: ${{ github.event.pull_request.head.ref || github.ref }}
      version_type: commit
      architecture: ${{ matrix.architecture }}
      cachix_cache_name: contracts
      build_file: ethereum/bindings/Cargo.toml
      build_command: ${{ matrix.build_command }}
      binary: hopr-contract-addresses
      runner: ${{ matrix.runner }}
    secrets:
      gcp_service_account: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      gpg_private_key: ${{ secrets.GPG_HOPRNET_PRIVATE_KEY }}
