name: Merge
on:
  pull_request:
    types:
      - closed
    branches:
      - main
concurrency:
  group: merge-${{ github.event.pull_request.base.ref }}
  cancel-in-progress: false
jobs:
  build-library:
    name: Library ${{ matrix.architecture }}
    if: github.event.pull_request.merged == true
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: x86_64-linux
            runner: self-hosted-hoprnet-bigger
            build_command: nix build -L .#lib-hopr-bindings-x86_64-linux
    uses: hoprnet/hopr-workflows/.github/workflows/build-library.yaml@build-library-v1
    permissions:
      contents: read
    with:
      source_branch: ${{ github.event.pull_request.base.ref }}
      architecture: ${{ matrix.architecture }}
      cachix_cache_name: contracts
      build_file: ethereum/bindings/Cargo.toml
      build_command: ${{ matrix.build_command }}
      runner: ${{ matrix.runner }}
    secrets:
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
  coverage:
    name: Coverage
    if: github.event.pull_request.merged == true
    uses: hoprnet/hopr-workflows/.github/workflows/tests.yaml@268553d7984344080e3dc65eb92778c9103af7ec # workflow-tests-v3
    with:
      source_branch: ${{ github.event.pull_request.base.ref }}
      unit_tests: false
      integration_tests: false
      unit_coverage: true
      unconditional: true
      unit_coverage_command: "nix run .#coverage-unit"
      runner: self-hosted-hoprnet-bigger
    secrets:
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      codecov_token: ${{ secrets.CODECOV_TOKEN }}
  notify:
    name: Notify failure
    needs:
      - build-library
      - coverage
    if: ${{ always() && github.event.pull_request.merged == true && !success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Notify failed merge pipeline
        uses: zulip/github-actions-zulip/send-message@e4c8f27c732ba9bd98ac6be0583096dea82feea5 # v1.0.2
        with:
          api-key: ${{ secrets.ZULIP_API_KEY }}
          email: ${{ secrets.ZULIP_EMAIL }}
          organization-url: "https://hopr.zulipchat.com"
          type: "stream"
          to: "HOPRd"
          topic: "main"
          content: |
            The merge pipeline has failed for pull request [#${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
