name: Close release
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: Version type after release
        required: true
        type: choice
        default: "patch"
        options:
          - rc
          - patch
          - minor
          - major
concurrency:
  group: release
  cancel-in-progress: false
jobs:
  build-library:
    name: Library ${{ matrix.architecture }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - architecture: x86_64-linux
            runner: self-hosted-hoprnet-bigger
            build_command: nix build -L .#lib-hopr-bindings-x86_64-linux
    uses: hoprnet/hopr-workflows/.github/workflows/build-library.yaml@build-library-v1
    permissions:
      contents: read
    with:
      source_branch: ${{ github.ref }}
      architecture: ${{ matrix.architecture }}
      cachix_cache_name: contracts
      build_file: ethereum/bindings/Cargo.toml
      build_command: ${{ matrix.build_command }}
      runner: ${{ matrix.runner }}
    secrets:
      cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
  release:
    name: Close release
    needs:
      - build-library
    runs-on: self-hosted-hoprnet-small
    permissions:
      contents: write
    steps:
      - name: Release version
        uses: hoprnet/hopr-workflows/actions/release-version@27fb7c9ad22da3361b1fb783c61ce06aa39dd62a # release-version-v2
        with:
          source_branch: ${{ github.ref_name }}
          file: Cargo.toml
          release_type: "${{ inputs.release_type }}"
          package_name: hopr-contract-addresses
          cachix_cache_name: "contracts"
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN }}
          zulip_api_key: ${{ secrets.ZULIP_API_KEY }}
          zulip_email: ${{ secrets.ZULIP_EMAIL }}
          zulip_channel: "HOPRd"
          zulip_topic: "Releases"
          gcp_service_account: ${{ secrets.GOOGLE_HOPRASSOCIATION_CREDENTIALS_REGISTRY }}
          github_token: ${{ secrets.GH_RUNNER_TOKEN }}
